#!/usr/bin/env node

const http = require('http');
const fs = require('fs');
const path = require('path');
const sqlite3 = require('sqlite3');
const crypto = require('crypto');

const basedir = 'build';
const port = process.env.PORT || 3001;
let id = crypto.randomBytes(16).toString("hex");
let volumeid = 0;
let sessionid = 0;

http.createServer(function(request, response) {
    const range = request.headers.range;

    let data = '';
    request.on('data', function (chunk) {
        data += chunk;
    });

    if (range) {
        console.log(request.method, request.url, range);
    } else {
        console.log(request.method, request.url);
    }

    let filePath = request.url;
    if (request.url === '/') {
        filePath = '/index.html';
    }

    const extname = String(path.extname(filePath)).toLowerCase();
    let contentType = 'text/html';
    const mimeTypes = {
        '.html': 'text/html',
        '.js': 'text/javascript',
        '.css': 'text/css',
        '.json': 'application/json',
        '.png': 'image/png',
        '.jpg': 'image/jpg',
        '.gif': 'image/gif',
        '.svg': 'image/svg+xml',
        '.wav': 'audio/wav',
        '.mp4': 'video/mp4',
        '.woff': 'application/font-woff',
        '.ttf': 'application/font-ttf',
        '.otf': 'application/font-otf'
    };

    contentType = mimeTypes[extname] || 'application/octet-stream';

    if (request.method === 'GET') {
        fs.readFile(basedir + filePath, function(error, content) {
            if (error) {
                if (error.code === 'ENOENT') {
                    console.log('404: ' + basedir + filePath);
                    console.log(error);
                    response.writeHead(404);
                    response.end();
                } else {
                    console.log('500: ' + filePath);
                    response.writeHead(500);
                    response.end('Server error: ' + error.code);
                }
            } else {
                if (range) {
                    const re = /^bytes=([0-9]+)-([0-9]+)$/;
                    const match = range.match(re);
                    if (match) {
                        const rangeStart = parseInt(match[1], 10);
                        const rangeEnd = parseInt(match[2], 10);
                        content = content.slice(rangeStart, rangeEnd + 1);
                    }
                }
                response.writeHead(200, {
                    'Content-Type'   : contentType,
                    'Content-Length' : content.length,
                    'Access-Control-Allow-Origin': '*',
                    'Access-Control-Allow-Methods': 'GET',
                    'Access-Control-Allow-Headers': 'Range'
                });
                response.end(content, 'utf-8');
            }
        });
    } else if (request.method === 'HEAD' || request.method === 'OPTIONS') {
        fs.lstat(basedir + filePath, function(error, stat) {
            if (error) {
                if (error.code === 'ENOENT') {
                    console.log('404: ' + filePath);
                    response.writeHead(404);
                    response.end();
                } else {
                    console.log('500: ' + filePath);
                    response.writeHead(500);
                    response.end('Server error: ' + error.code);
                }
            } else {
                response.writeHead(200, {
                    'Content-Type'   : contentType,
                    'Content-Length' : stat.size,
                    'Access-Control-Allow-Origin': '*',
                    'Access-Control-Allow-Methods': 'GET',
                    'Access-Control-Allow-Headers': 'Range'
                });
                response.end();
            }
        });
    } else if (request.method === 'POST') {
        fs.lstat(basedir + filePath, function (error, stat) {
            if (error) {
                if (error.code === 'ENOENT') {
                    console.log('404: ' + filePath);
                    response.writeHead(404);
                    response.end();
                } else {
                    console.log('500: ' + filePath);
                    response.writeHead(500);
                    response.end('Server error: ' + error.code);
                }
            } else {

                response.writeHead(200, {
                    'Content-Type': contentType,
                    'Content-Length': stat.size,
                    'Access-Control-Allow-Origin': '*',
                    'Access-Control-Allow-Methods': 'POST',
                    'Access-Control-Allow-Headers': 'Range'
                });
                response.end();



                let parsed = JSON.parse(data);

                let db = new sqlite3.Database('test.db', (err) => {
                    if (err) {
                        return console.error(err.message);
                    }
                    console.log('Connected to the in-memory SQlite database.')
                });

                if(parsed.type === "sv") {
                    let sql1 = 'UPDATE Volumes SET Count = Count + 1 WHERE Url = ?';
                    db.run(sql1, parsed.volume, function (err) {
                        if (err) {
                            return console.log(err.message);
                        }
                        console.log('Increment');
                    });

                    let sql2 = 'INSERT INTO Sessions (UUID, VolumeID) VALUES(?, ?)';
                    db.run(sql2, [id, parsed.id], function (err) {
                        if (err) {
                            return console.log(err.message);
                        }
                    });

                    volumeid = parsed.id;

                    let sql3 = 'SELECT Id id FROM Sessions WHERE UUID = ?';
                    db.get(sql3, [id], function (err, row) {
                        if (err) {
                            return console.log(err.message);
                        }
                        sessionid = row.id;
                    });
                }

                else if (parsed.type === "tf") {

                    let sql = 'INSERT INTO Functions (TF, Kamera, Timestamp, SessionID, VolumeID) VALUES(?, ?, ?, ?, ?)';
                    db.run(sql, [JSON.stringify(parsed.bumps), JSON.stringify(parsed.camera), parsed.time, sessionid, volumeid], function (err) {
                        if (err) {
                            return console.log(err.message);
                        }
                        console.log('A row has been inserted!');
                    });

                }
                db.close();
            }
        })
    } else {
        response.writeHead(404);
        response.end();
    }

}).listen(port);

console.log('Listening on port ' + port);
